let customerSearchTimer=null;
function scheduleCustomerSearch(){clearTimeout(customerSearchTimer);customerPage=1;customerSearchTimer=setTimeout(()=>{customerSearchTimer=null;renderCustomers()},250)}
$('#customerSearchInput').addEventListener('input',event=>{if(!event.isComposing)scheduleCustomerSearch()});
$('#customerSearchInput').addEventListener('compositionend',scheduleCustomerSearch);
for(const selector of ['#customerContactFilter','#customerSort'])$(selector).addEventListener('change',()=>{clearTimeout(customerSearchTimer);customerSearchTimer=null;customerPage=1;renderCustomers()});
$('#customerPagination').addEventListener('click',event=>{
  const button=event.target.closest('[data-customer-page]');
  if(!button||button.disabled)return;
  const last=Number($('#customerPageInput').max)||1;
  customerPage=button.dataset.customerPage==='first'?1:button.dataset.customerPage==='previous'?customerPage-1:button.dataset.customerPage==='next'?customerPage+1:last;
  customerPage=Math.min(Math.max(customerPage,1),last);
  clearTimeout(customerSearchTimer);customerSearchTimer=null;
  renderCustomers();
  $('#customerList').scrollIntoView({behavior:'smooth',block:'start'});
});
$('#customerPageInput').addEventListener('change',event=>{
  const last=Number(event.target.max)||1;
  customerPage=Math.min(Math.max(Math.trunc(Number(event.target.value))||1,1),last);
  clearTimeout(customerSearchTimer);customerSearchTimer=null;
  renderCustomers();
  $('#customerList').scrollIntoView({behavior:'smooth',block:'start'});
});
$('#newCustomerButton').addEventListener('click',()=>openCustomerForm());$('#closeCustomerDetail').addEventListener('click',()=>$('#customerDetail').classList.add('role-hidden'));
$('#customerList').addEventListener('click',event=>{const row=event.target.closest('[data-customer-id]');if(row)openCustomerDetail(row.dataset.customerId)});
$('#customerForm').elements.name.addEventListener('input',event=>{clearTimeout(event.target._duplicateTimer);event.target._duplicateTimer=setTimeout(()=>showCustomerDuplicateWarning(event.target.value,$('#customerForm').elements.customerId.value),220)});
$('#customerForm').addEventListener('submit',async event=>{if(event.submitter?.value==='cancel')return;event.preventDefault();if(!canEditCustomers()){showToast('Bu işlem için müşteri düzenleme yetkisi gerekir.');return}const form=event.currentTarget,data=new FormData(form),id=data.get('customerId'),payload={name:data.get('name'),address:data.get('address'),note:data.get('note')},hasDuplicate=await showCustomerDuplicateWarning(payload.name,id);if(!id&&hasDuplicate&&!await askConfirm('Aynı firma adında başka lokasyonlar bulunuyor. Bu adresi yeni bir müşteri lokasyonu olarak eklemek istiyor musunuz?',{title:'Yeni lokasyon ekle',confirmLabel:'Ekle'}))return;if(id)await customerDataService.update(id,payload);else await customerDataService.create(payload);form.closest('dialog').close();await renderCustomers();if(id)openCustomerDetail(id);showToast(id?'Müşteri bilgileri güncellendi.':'Yeni müşteri lokasyonu eklendi.')});
$('#contactForm').addEventListener('submit',async event=>{if(event.submitter?.value==='cancel')return;event.preventDefault();if(!canEditCustomers()){showToast('Bu işlem için kontak düzenleme yetkisi gerekir.');return}const data=new FormData(event.currentTarget),customerId=data.get('customerId');await customerDataService.saveContact(customerId,{id:data.get('contactId'),firstName:data.get('firstName'),lastName:data.get('lastName'),email:data.get('email'),mobile:data.get('mobile'),phone:data.get('phone'),primary:data.get('primary')==='on'});event.currentTarget.closest('dialog').close();await renderCustomers();openCustomerDetail(customerId);showToast(data.get('contactId')?'Kontak bilgileri güncellendi.':'Yeni kontak eklendi.')});
$('#customerDetailBody').addEventListener('input',event=>{if(!event.target.matches('[data-customer-detail-search]'))return;const term=normalizeSearch(event.target.value);$$('#customerDetailBody [data-detail-search]').forEach(item=>item.classList.toggle('detail-search-hidden',Boolean(term)&&!item.dataset.detailSearch.includes(term)))});
$('#customerDetailBody').addEventListener('click',async event=>{const viewContact=event.target.closest('[data-view-contact]'),restoreCustomer=event.target.closest('[data-restore-customer]');if(viewContact){openCustomerContactView(viewContact.dataset.viewContact);return}if(restoreCustomer){await customerDataService.restore(restoreCustomer.dataset.restoreCustomer);await renderCustomers();openCustomerDetail(restoreCustomer.dataset.restoreCustomer);showToast('Müşteri yeniden aktifleştirildi.')}});
$$('[data-close-contact-view]').forEach(button=>button.addEventListener('click',()=>$('#customerContactViewDialog').close()));
function enableInformationDialogBackdropClose(selector,closeHandler){const dialog=$(selector);dialog.addEventListener('pointerdown',event=>{if(event.target!==dialog)return;const rect=dialog.getBoundingClientRect(),outside=event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom;if(outside)closeHandler()})}
enableInformationDialogBackdropClose('#installationDetailDialog',closeInstallationDetail);enableInformationDialogBackdropClose('#customerContactViewDialog',()=>$('#customerContactViewDialog').close());enableInformationDialogBackdropClose('#serviceReportViewDialog',closeServiceReportView);
$('#customerDetailBody').addEventListener('click',async event=>{const editCustomer=event.target.closest('[data-edit-customer]'),deleteCustomer=event.target.closest('[data-delete-customer]'),newContact=event.target.closest('[data-new-contact]'),editContact=event.target.closest('[data-edit-contact]'),deleteContact=event.target.closest('[data-delete-contact]'),installation=event.target.closest('[data-customer-installation]');if(editCustomer){const customer=await customerDataService.get(editCustomer.dataset.editCustomer);openCustomerForm(customer);return}if(deleteCustomer){const customer=await customerDataService.get(deleteCustomer.dataset.deleteCustomer);if(!customer||!await askConfirm(customer.installations.length||customer.contacts.length?'Bu müşteri geçmiş kayıtları korumak için arşivlenecek. Devam edilsin mi?':'Bu müşteri tamamen silinsin mi?',{title:customer.installations.length||customer.contacts.length?'Müşteriyi arşivle':'Müşteriyi sil',confirmLabel:customer.installations.length||customer.contacts.length?'Arşivle':'Sil',tone:'danger'}))return;const result=await customerDataService.remove(customer.id);$('#customerDetail').classList.add('role-hidden');await renderCustomers();showToast(result.mode==='deleted'?'Müşteri silindi.':'Müşteri arşivlendi.');return}if(newContact){openContactForm(newContact.dataset.newContact);return}if(editContact){openContactForm(activeCustomerId,editContact.dataset.editContact);return}if(deleteContact){if(!await askConfirm('Bu kontak silinsin mi?',{title:'Kontak sil',confirmLabel:'Sil',tone:'danger'}))return;await customerDataService.removeContact(deleteContact.dataset.deleteContact);await renderCustomers();openCustomerDetail(activeCustomerId);showToast('Kontak silindi.');return}if(installation){$('#customerDetail').classList.add('role-hidden');openInstallationDetail(Number(installation.dataset.customerInstallation))}});
