/* v144 - Ana kuruluma bağlı, bağımsız Goodwill operasyon görünümü */
const expandedGoodwillParents=new Set();
function visibleGoodwillOrders(){if(!currentUser)return[];return workOrders.filter(order=>order.workOrderType==='goodwill').filter(order=>{if(hasRole('admin','supervisor'))return true;if(currentUser.role==='sales')return ownsSalesRecord(order)||order.goodwill?.requestedByUsername===currentUser.username;return currentUser.role==='technician'&&installationAssignedToUser(order)})}
function goodwillStatusGroup(order){if(order.goodwillStage==='goodwillRejected'||order.workflowStage==='goodwillRejected')return'rejected';if(order.workflowStage==='completed')return'completed';if(['awaitingPlanning','planned','inService'].includes(order.workflowStage))return'active';return'approval'}
function goodwillActualHours(order){return(order.serviceVisits||[]).reduce((total,visit)=>total+serviceVisitHours(visit),0)}
function goodwillPlanDate(order){return serviceWorkPlans(order)[0]?.date||'—'}
function goodwillLastActivity(order){return order.goodwill?.history?.at?.(-1)?.at||order.updatedAt||order.createdAt||order.goodwill?.requestedAt||''}
function goodwillContextMarkup(order){const parent=parentInstallationFor(order),actions=workOrderActionMarkup(order);return `<article class="goodwill-operation-card" data-goodwill-card="${order.id}"><div class="goodwill-branch" aria-hidden="true"></div><header><div><em>${escapeHtml(order.goodwill?.type||'Goodwill')}</em><strong>${escapeHtml(order.workOrderNumber||'GW')}</strong><small>${escapeHtml(order.goodwill?.category||'Kategori belirtilmedi')}</small></div><span class="status ${statusClass(order.status)}">${escapeHtml(order.status)}</span></header><div class="goodwill-operation-grid"><span><small>BAĞLI ANA KURULUM</small><b>${escapeHtml(parent?.salesOrderNumber||order.salesOrderNumber||'—')}</b></span><span><small>MÜŞTERİ</small><b>${escapeHtml(parent?.customer||order.customer||'—')}</b></span><span><small>PLANLANAN</small><b>${escapeHtml(goodwillPlanDate(order))}</b></span><span><small>GERÇEKLEŞEN</small><b>${escapeHtml(order.completedAt?formatAssignmentDate(order.completedAt):'—')}</b></span><span><small>TAHMİNİ / GERÇEKLEŞEN</small><b>${escapeHtml(order.goodwill?.estimatedHours||0)} / ${escapeHtml(goodwillActualHours(order))} adam-saat</b></span></div><p>${escapeHtml(order.goodwill?.reason||'Açıklama girilmemiş.')}</p><footer><button type="button" class="row-action secondary-action" data-goodwill-parent-detail="${parent?.id||''}">Ana işi ve ayrıntıları gör</button>${actions}</footer></article>`}
function renderLinkedGoodwillRows(){if(!$('#allInstallationRows'))return;const visibleIds=new Set(visibleGoodwillOrders().map(order=>Number(order.id)));$('#allInstallationRows').querySelectorAll('tr[data-record-id]').forEach(row=>{const parentId=Number(row.dataset.recordId),orders=goodwillWorkOrders(parentId).filter(order=>visibleIds.has(Number(order.id)));if(!orders.length)return;const active=orders.filter(order=>!['completed','rejected'].includes(goodwillStatusGroup(order))).length,firstCell=row.querySelector('td:first-child');firstCell?.insertAdjacentHTML('beforeend',`<button type="button" class="goodwill-expand-button" data-toggle-goodwill="${parentId}" aria-expanded="${expandedGoodwillParents.has(parentId)}"><span>↳</span> ${orders.length} Goodwill${active?` · ${active} aktif`:''}</button>`);row.insertAdjacentHTML('afterend',`<tr class="goodwill-child-row${expandedGoodwillParents.has(parentId)?' is-open':''}" data-goodwill-parent-row="${parentId}"><td colspan="9"><div class="goodwill-child-stack">${orders.map(goodwillContextMarkup).join('')}</div></td></tr>`)})}
function renderGoodwillWorkspace(){const target=$('#goodwillList');if(!target)return;const all=visibleGoodwillOrders(),term=normalizeSearch($('#goodwillSearchInput')?.value||''),status=$('#goodwillStatusFilter')?.value||'',type=$('#goodwillTypeFilter')?.value||'';const filtered=all.filter(order=>{const parent=parentInstallationFor(order),haystack=normalizeSearch(`${order.workOrderNumber} ${order.salesOrderNumber} ${parent?.customer||order.customer} ${order.goodwill?.type} ${order.goodwill?.category} ${order.goodwill?.requestedBy} ${order.goodwill?.reason}`);return(!term||haystack.includes(term))&&(!status||goodwillStatusGroup(order)===status)&&(!type||order.goodwill?.type===type)}).sort((a,b)=>new Date(goodwillLastActivity(b))-new Date(goodwillLastActivity(a)));$('#goodwillTotalCount').textContent=all.length;$('#goodwillApprovalCount').textContent=all.filter(order=>goodwillStatusGroup(order)==='approval').length;$('#goodwillActiveCount').textContent=all.filter(order=>goodwillStatusGroup(order)==='active').length;$('#goodwillCompletedCount').textContent=all.filter(order=>goodwillStatusGroup(order)==='completed').length;const nav=$('#goodwillNavCount'),navItem=$('#goodwillNavItem');if(nav)nav.textContent=all.length;if(navItem)navItem.classList.toggle('role-hidden',!all.length);target.innerHTML=filtered.length?filtered.map(goodwillContextMarkup).join(''):'<div class="goodwill-empty"><strong>Goodwill kaydı bulunmuyor</strong><span>Bu görünümde yetkinize ve filtrelere uygun bağlı iş emri yok.</span></div>'}
const renderV144Base=render;render=()=>{renderV144Base();renderLinkedGoodwillRows();renderGoodwillWorkspace()};
const showViewV144Base=showView;showView=name=>{showViewV144Base(name);if(name==='goodwill')renderGoodwillWorkspace()};
const openGoodwillFormV144Base=openGoodwillForm;openGoodwillForm=(parentId,goodwillId=null)=>{openGoodwillFormV144Base(parentId,goodwillId);const record=goodwillId?workOrders.find(item=>Number(item.id)===Number(goodwillId)):null,field=$('#goodwillForm')?.elements.goodwillCategory;if(field)field.value=record?.goodwill?.category||''};
const openGoodwillReviewV144Base=openGoodwillReview;openGoodwillReview=id=>{openGoodwillReviewV144Base(id);const item=operationalRecord(id);if(item&&$('#goodwillReviewDialog').open)$('#goodwillReviewContent').insertAdjacentHTML('beforeend',`${detailField('Kapsam',item.goodwill?.category||'Kategori belirtilmedi')}${detailField('Bağlı ana kurulum',parentInstallationFor(item)?.salesOrderNumber||item.salesOrderNumber)}`)};
$('#goodwillForm').addEventListener('submit',event=>{if(event.submitter?.value==='cancel')return;const form=event.currentTarget,parentId=Number(form.elements.parentInstallationId.value),existingId=Number(form.elements.goodwillId.value),category=form.elements.goodwillCategory.value;queueMicrotask(()=>{const record=existingId?workOrders.find(item=>Number(item.id)===existingId):workOrders.filter(item=>Number(item.parentInstallationId)===parentId&&item.goodwill?.requestedByUsername===currentUser?.username).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))[0];if(!record)return;const parent=parentInstallationFor(record);record.goodwill={...(record.goodwill||{}),category};record.parentReference={installationId:parent?.id||parentId,salesOrderNumber:parent?.salesOrderNumber||record.salesOrderNumber,customer:parent?.customer||record.customer,installationCompletedAt:parent?.completedAt||null};record.operationKind='goodwill';record.schemaVersion=2;record.revision=Number(record.revision||0)+1;record.updatedAt=new Date().toISOString();delete record.pendingSalesChangeRequest;delete record.pendingContinuationPlanning;delete record.salesChangeMayAffectPlanning;saveOperationalData();render()})},true);
const openServiceEntryV144Base=openServiceEntry;openServiceEntry=id=>{openServiceEntryV144Base(id);const item=operationalRecord(id);if(item?.workOrderType==='goodwill'&&$('#serviceEntryDialog').open){$('#serviceEntryDialog .eyebrow').textContent='GOODWILL SAHA KAYDI';$('#serviceEntryDialog h2').textContent=`${item.goodwill?.type||'Goodwill'} Raporu`;$('#serviceRecordTitle').textContent=`${item.workOrderNumber} · Ana kurulum ${parentInstallationFor(item)?.salesOrderNumber||item.salesOrderNumber} · ${item.customer}`}};
function handleGoodwillNavigation(event){const toggle=event.target.closest('[data-toggle-goodwill]'),parentDetail=event.target.closest('[data-goodwill-parent-detail]');if(toggle){event.preventDefault();event.stopPropagation();const id=Number(toggle.dataset.toggleGoodwill);expandedGoodwillParents.has(id)?expandedGoodwillParents.delete(id):expandedGoodwillParents.add(id);render();return}if(parentDetail){event.preventDefault();event.stopPropagation();showView('installations');openInstallationDetail(Number(parentDetail.dataset.goodwillParentDetail))}}
$('#allInstallationRows')?.addEventListener('click',handleGoodwillNavigation,true);$('#goodwillList')?.addEventListener('click',handleGoodwillNavigation,true);
$('#goodwillList')?.addEventListener('click',event=>{const review=event.target.closest('[data-goodwill-review-id]'),edit=event.target.closest('[data-goodwill-edit-id]'),plan=event.target.closest('[data-plan-installation-id]'),service=event.target.closest('[data-service-entry-id]');if(review)return openGoodwillReview(Number(review.dataset.goodwillReviewId));if(edit){const order=operationalRecord(Number(edit.dataset.goodwillEditId));if(order)return openGoodwillForm(order.parentInstallationId,order.id)}if(plan)return openPlanning(Number(plan.dataset.planInstallationId));if(service)return openServiceEntry(Number(service.dataset.serviceEntryId))});
['goodwillSearchInput','goodwillStatusFilter','goodwillTypeFilter'].forEach(id=>$('#'+id)?.addEventListener(id==='goodwillSearchInput'?'input':'change',renderGoodwillWorkspace));
function csvCell(value){return`"${String(value??'').replaceAll('"','""')}"`}
$('#exportGoodwillReport')?.addEventListener('click',()=>{const rows=visibleGoodwillOrders().map(order=>{const parent=parentInstallationFor(order),plans=serviceWorkPlans(order),visits=order.serviceVisits||[];return[order.workOrderNumber,order.goodwill?.type,order.goodwill?.category||'Kategori belirtilmedi',parent?.salesOrderNumber||order.salesOrderNumber,parent?.customer||order.customer,order.status,order.goodwill?.requestedBy,order.goodwill?.customerRequestDate,plans.length,goodwillPlanDate(order),visits.length,order.goodwill?.estimatedHours||0,goodwillActualHours(order),order.completedAt?formatAssignmentDate(order.completedAt):'',order.goodwill?.reason]});const headings=['GW No','Goodwill Tipi','Kapsam','Bağlı SO','Müşteri','Durum','Talep Eden','Müşteri Talep Tarihi','Plan Sayısı','İlk Plan Tarihi','Ziyaret Sayısı','Tahmini Adam-Saat','Gerçekleşen Adam-Saat','Tamamlanma Tarihi','Talep Nedeni'],csv='\uFEFF'+[headings,...rows].map(row=>row.map(csvCell).join(';')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`goodwill-raporu-${localDateKey()}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$('#notificationList')?.addEventListener('click',event=>{const open=event.target.closest('[data-open-notification]');if(!open)return;const notification=userNotifications().find(item=>item.id===open.dataset.openNotification),order=notification&&workOrders.find(item=>Number(item.id)===Number(notification.installationId));if(!order)return;event.preventDefault();event.stopImmediatePropagation();setNotificationStatus(notification.id,{readAt:new Date().toISOString()});closeNotificationCenter();showView('goodwill');requestAnimationFrame(()=>{const card=$(`[data-goodwill-card="${order.id}"]`);card?.scrollIntoView({behavior:'smooth',block:'center'});card?.classList.add('goodwill-focus');setTimeout(()=>card?.classList.remove('goodwill-focus'),2200)})},true);
let goodwillMigrationChanged=false;workOrders.forEach(order=>{if(order.workOrderType!=='goodwill')return;if(!order.schemaVersion){order.schemaVersion=2;goodwillMigrationChanged=true}if(!Number(order.revision)){order.revision=1;goodwillMigrationChanged=true}if(!Array.isArray(order.goodwill?.history)){order.goodwill={...(order.goodwill||{}),history:[]};goodwillMigrationChanged=true}});if(goodwillMigrationChanged)saveOperationalData();
if(currentUser)render();
initializeReportingV158();
storageBooting=false;
