const seedInstallations = [
  {id:1,customer:'Anka Endüstri',salesOrderNumber:'SO-2026-1842',requestDate:'12 Ağu 2026',salesEngineer:'İrem Oğuzkan',ptd:'PTD-0831',status:'Devam ediyor',date:'27 Ağu 2026',tech:'Gürcan Girgin',initials:'GG',progress:65},
  {id:2,customer:'Marmara Teknoloji',salesOrderNumber:'SO-2026-1798',requestDate:'14 Ağu 2026',salesEngineer:'İrem Oğuzkan',ptd:'PTD-0814',status:'Planlandı',date:'28 Ağu 2026',tech:'Cihan Eraslan',initials:'CE',progress:20},
  {id:3,customer:'Nova Ambalaj',salesOrderNumber:'SO-2026-1765',requestDate:'15 Ağu 2026',salesEngineer:'Remzi Sakin',ptd:'—',status:'Sevkiyat bekliyor',date:'02 Eyl 2026',tech:'Atama bekliyor',initials:'?',progress:10},
  {id:4,customer:'Eksen Otomasyon',salesOrderNumber:'SO-2026-1699',requestDate:'17 Ağu 2026',salesEngineer:'İrem Oğuzkan',ptd:'PTD-0779',status:'Süre aşıldı',date:'25 Ağu 2026',tech:'Zemzem Daşdemir',initials:'ZD',progress:82},
  {id:5,customer:'Atlas Makina',salesOrderNumber:'SO-2026-1684',requestDate:'18 Ağu 2026',salesEngineer:'Bora Erdem',ptd:'PTD-0764',status:'Planlandı',date:'04 Eyl 2026',tech:'Raşit Abbasoğlu',initials:'RA',progress:15},
  {id:6,customer:'Pera Üretim',salesOrderNumber:'SO-2026-1651',requestDate:'19 Ağu 2026',salesEngineer:'Oğulcan Çoban',ptd:'—',status:'Devam ediyor',date:'05 Eyl 2026',tech:'Cihan Eraslan',initials:'CE',progress:48},
  {id:7,customer:'Kuzey Robotik',salesOrderNumber:'SO-2026-1602',requestDate:'20 Ağu 2026',salesEngineer:'Bora Erdem',ptd:'PTD-0702',status:'Planlandı',date:'08 Eyl 2026',tech:'Zemzem Daşdemir',initials:'ZD',progress:25},
  {id:8,customer:'Delta Sistem',salesOrderNumber:'SO-2026-1588',requestDate:'21 Ağu 2026',salesEngineer:'Oğulcan Çoban',ptd:'PTD-0688',status:'Süre aşıldı',date:'24 Ağu 2026',tech:'Gürcan Girgin',initials:'GG',progress:92}
];

let installations = (JSON.parse(localStorage.getItem('cps-installations') || 'null') || seedInstallations).map(item=>{const sample=seedInstallations.find(seed=>seed.id===item.id);const workflowStage=item.workflowStage||(item.status==='Taslak'?'draft':item.status==='Planlama bekliyor'?'awaitingPlanning':'planned');return {...item,workflowStage,salesOrderNumber:item.salesOrderNumber||item.so,requestDate:workflowStage==='draft'?'—':item.requestDate||sample?.requestDate||'—',salesEngineer:item.salesEngineer||sample?.salesEngineer||'Atama bekliyor'}});
const retiredDemoAssignees={'Ahmet Kaya':['Gürcan Girgin','GG'],'Selin Demir':['Cihan Eraslan','CE'],'Murat Çelik':['Zemzem Daşdemir','ZD']};
installations=installations.map(item=>retiredDemoAssignees[item.tech]?{...item,tech:retiredDemoAssignees[item.tech][0],initials:retiredDemoAssignees[item.tech][1]}:item);
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const roleDescriptions={admin:'Tüm kurulum operasyonlarının ve kullanıcıların genel görünümü.',sales:'Satış ve sevkiyat kayıtlarınızın bugünkü görünümü.',supervisor:'Kurulum operasyonlarının bugünkü görünümü.',technician:'Size atanan kurulumların bugünkü görünümü.'};
const userDirectory=(Array.isArray(window.CPS_USER_DATA)?window.CPS_USER_DATA:[]).filter(user=>user.active!==false).map(user=>{const parts=String(user.name||'').trim().split(/\s+/);return {...user,firstName:parts[0]||'',initials:parts.map(part=>part[0]).join('').toLocaleUpperCase('tr-TR'),description:roleDescriptions[user.role]||'Kurulum operasyonlarının bugünkü görünümü.'}});
let currentUser=null;
let draftOrderProducts=[];
let editOrderProducts=[];
let editingInstallationId=null;
let language='tr';
const accountDirectory=Array.isArray(window.CPS_ACCOUNT_DATA)?window.CPS_ACCOUNT_DATA:[];
const productDirectory=(Array.isArray(window.CPS_PRODUCT_DATA)?window.CPS_PRODUCT_DATA:[]).map(product=>({...product,searchPartNo:normalizeSearch(product.partNo)}));
let accountMatches=[];
let activeAccountMatch=-1;
let pendingAccount=null;
let activeAccountSearch=null;
let pendingAddressField=null;
const accountSearchConfigs=[
  {input:'#customerNameInput',list:'#customerSuggestions',address:'address',label:'kurulum adresi'},
  {input:'#mtbNameInput',list:'#mtbSuggestions',address:'mtbAddress',label:'MTB kurulum adresi'},
  {input:'#endUserNameInput',list:'#endUserSuggestions',address:'endUserAddress',label:'son kullanıcı kurulum adresi'}
];
let productMatches=[];
let activeProductMatch=-1;
let productSearchContext=null;
const translations={
  tr:{overview:'Genel Bakış',installations:'Kurulumlar',calendar:'Takvim',customers:'Müşteriler',products:'Ürünler',reports:'Raporlar',users:'Kullanıcılar'},
  en:{overview:'Overview',installations:'Installations',calendar:'Calendar',customers:'Customers',products:'Products',reports:'Reports',users:'Users'}
};

function hasRole(...roles){return Boolean(currentUser&&(currentUser.role==='admin'||roles.includes(currentUser.role)))}
function populateUserSelectors(){const salesUsers=userDirectory.filter(user=>['admin','sales'].includes(user.role)),technicians=userDirectory.filter(user=>user.role==='technician');$$('select[name="salesEngineer"]').forEach(select=>{const selected=select.value;select.innerHTML=salesUsers.map(user=>`<option>${escapeHtml(user.name)}</option>`).join('');if([...select.options].some(option=>option.value===selected))select.value=selected});$$('select[name="technician"]').forEach(select=>{const selected=select.value;select.innerHTML=`<option value="">Teknisyen seçin</option>${technicians.map(user=>`<option>${escapeHtml(user.name)}</option>`).join('')}`;if([...select.options].some(option=>option.value===selected))select.value=selected})}
function renderUsers(){const rows=$('#userRows');if(!rows)return;rows.innerHTML=userDirectory.map(user=>`<tr><td><div class="technician"><span class="mini-avatar">${escapeHtml(user.initials)}</span><strong>${escapeHtml(user.name)}</strong></div></td><td>${escapeHtml(user.title)}</td><td><span class="status planned">${escapeHtml(user.roleLabel)}</span></td><td><code>${escapeHtml(user.username)}</code></td><td><span class="user-active"><i></i>Aktif</span></td></tr>`).join('')}
function renderQuickLogins(){const container=$('#quickLoginAccounts');if(!container)return;const roleOrder=['admin','supervisor','sales','technician'],roleNames={admin:'Yönetici',supervisor:'Servis Süpervisörü',sales:'Satış Mühendisi',technician:'Servis Teknisyeni'},users=roleOrder.map(role=>userDirectory.find(user=>user.role===role)).filter(Boolean);container.innerHTML=`<p>Demo hızlı giriş</p>${users.map(user=>`<button type="button" data-quick-login="${escapeHtml(user.username)}"><span class="demo-avatar">${escapeHtml(user.initials)}</span><span><b>${escapeHtml(roleNames[user.role])}</b><small>${escapeHtml(user.name)}</small></span></button>`).join('')}<small>Bir kullanıcı tipini seçerek doğrudan giriş yapabilirsiniz.</small>`}
function recordDate(item){const value=item.plannedDateIso||item.requestDateIso||item.estimatedInstallationDate||item.estimatedDeliveryDate;if(value&&/^\d{4}-\d{2}-\d{2}$/.test(value))return new Date(`${value}T12:00:00`);const display=[item.date,item.requestDate].find(text=>/\d{4}/.test(text||'')),match=String(display||'').match(/(\d{1,2})\s+([A-Za-zÇĞİÖŞÜçğıöşü]+)\s+(\d{4})/),months={oca:0,şub:1,mar:2,nis:3,may:4,haz:5,tem:6,ağu:7,eyl:8,eki:9,kas:10,ara:11};return match&&months[match[2].toLocaleLowerCase('tr-TR')]!==undefined?new Date(Number(match[3]),months[match[2].toLocaleLowerCase('tr-TR')],Number(match[1])):null}
function populateInstallationFilters(){const years=[...new Set(installations.map(item=>recordDate(item)?.getFullYear()).filter(Boolean))].sort((a,b)=>b-a),sales=[...new Set(installations.map(item=>item.salesEngineer).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'tr')),customers=[...new Set(installations.map(item=>item.customer).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'tr'));$('#yearFilter').innerHTML='<option value="">Tüm yıllar</option>'+years.map(value=>`<option>${value}</option>`).join('');$('#salesFilter').innerHTML='<option value="">Tüm satış mühendisleri</option>'+sales.map(value=>`<option>${escapeHtml(value)}</option>`).join('');$('#customerFilter').innerHTML='<option value="">Tüm müşteriler</option>'+customers.map(value=>`<option>${escapeHtml(value)}</option>`).join('')}
function updateFilterCount(){const count=['yearFilter','quarterFilter','salesFilter','customerFilter','statusFilter'].filter(id=>$(`#${id}`)?.value).length,badge=$('#activeFilterCount');badge.textContent=count;badge.classList.toggle('role-hidden',!count)}

function statusClass(status){return {'Taslak':'draft','Devam ediyor':'progress','Planlandı':'planned','Tamamlandı':'completed','Planlama bekliyor':'waiting','Sevkiyat bekliyor':'waiting','Süre aşıldı':'overrun'}[status] || 'planned'}
function rowTemplate(item){return `<tr><td><strong>${escapeHtml(item.customer)}</strong><small>${escapeHtml(item.salesOrderNumber)} · ${escapeHtml(item.ptd)}</small></td><td><span class="status ${statusClass(item.status)}">${item.status}</span></td><td><strong>${item.date}</strong><small>09:00</small></td><td><div class="technician"><span class="mini-avatar">${item.initials}</span>${escapeHtml(item.tech)}</div></td><td><span class="progress-bar"><i style="width:${item.progress}%"></i></span><small>%${item.progress}</small></td><td><button class="row-action" aria-label="Detay">›</button></td></tr>`}
function installationRowTemplate(item){const canPlan=currentUser?.role==='supervisor',canEdit=currentUser?.role==='sales',canService=['supervisor','technician'].includes(currentUser?.role)&&!['draft','awaitingPlanning'].includes(item.workflowStage),canDelete=canEdit&&['draft','awaitingPlanning'].includes(item.workflowStage);const deleteAction=canDelete?`<button class="row-action planning-action danger-action" data-delete-installation-id="${item.id}">Sil</button>`:'';let actions;if(canPlan)actions=`<div class="row-actions"><button class="row-action planning-action secondary-action" data-installation-id="${item.id}">Planla</button>${canService?`<button class="row-action planning-action" data-service-entry-id="${item.id}">Servis kaydı</button>`:''}</div>`;else if(canEdit)actions=`<div class="row-actions"><button class="row-action planning-action secondary-action" data-record-edit-id="${item.id}">Düzenle</button>${item.workflowStage==='draft'?`<button class="row-action planning-action" data-send-planning-id="${item.id}">Planlamaya gönder</button>`:`<button class="row-action planning-action" data-installation-id="${item.id}">Sevkiyat</button>`}${deleteAction}</div>`;else if(canService)actions=`<button class="row-action planning-action" data-service-entry-id="${item.id}">Servis kaydı</button>`;else actions=`<button class="row-action" data-record-detail-id="${item.id}" aria-label="Detay">›</button>`;return `<tr class="${item.serviceOverrun?'service-overrun-row':''}" data-record-id="${item.id}" tabindex="0"><td><strong>${escapeHtml(item.customer)}</strong><small>${escapeHtml(item.ptd)}</small></td><td><strong>${escapeHtml(item.salesOrderNumber)}</strong></td><td>${escapeHtml(item.requestDate)}</td><td><strong>${escapeHtml(item.salesEngineer)}</strong></td><td><span class="status ${statusClass(item.status)}">${item.status}</span>${item.serviceOverrun?'<small class="overrun-label">PLANLANAN SÜRE AŞILDI</small>':''}</td><td><strong>${escapeHtml(item.date)}</strong>${item.plannedDuration?`<small>${item.plannedDuration} ${escapeHtml(item.plannedUnit)}</small>`:''}</td><td><div class="technician"><span class="mini-avatar">${item.initials}</span>${escapeHtml(item.tech)}</div></td><td><span class="progress-bar"><i style="width:${item.progress}%"></i></span><small>%${item.progress}</small></td><td>${actions}</td></tr>`}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function normalizeSearch(value){return String(value||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i')}
function hideAccountSuggestions(config=activeAccountSearch){if(config){$(config.list).classList.add('role-hidden');$(config.list).innerHTML=''}if(!config||activeAccountSearch===config){accountMatches=[];activeAccountMatch=-1;activeAccountSearch=null}}
function renderAccountSuggestions(query,config){if(activeAccountSearch&&activeAccountSearch!==config)hideAccountSuggestions(activeAccountSearch);activeAccountSearch=config;const normalized=normalizeSearch(query.trim());if(normalized.length<2){hideAccountSuggestions(config);return}accountMatches=accountDirectory.filter(account=>normalizeSearch(account.name).includes(normalized)).sort((a,b)=>{const aStart=normalizeSearch(a.name).startsWith(normalized),bStart=normalizeSearch(b.name).startsWith(normalized);return Number(bStart)-Number(aStart)||a.name.localeCompare(b.name,'tr')}).slice(0,8);activeAccountMatch=-1;const list=$(config.list);if(!accountMatches.length){hideAccountSuggestions(config);return}list.innerHTML=accountMatches.map((account,index)=>`<button type="button" role="option" data-account-index="${index}"><strong>${escapeHtml(account.name)}</strong>${account.address?`<small>${escapeHtml(account.address)}</small>`:''}</button>`).join('');list.classList.remove('role-hidden')}
function selectAccount(account,config=activeAccountSearch){if(!account||!config)return;$(config.input).value=account.name;hideAccountSuggestions(config);pendingAccount=account;pendingAddressField=config.address;if(!account.address){showToast('Bu firma için kayıtlı adres bulunamadı.');$(`[name="${config.address}"]`).focus();return}$('#selectedAccountName').textContent=account.name;$('#selectedAccountAddress').textContent=account.address;$('#selectedAddressQuestion').textContent=`Bu adres ${config.label} olarak kullanılsın mı?`;$('#addressSuggestionDialog').showModal()}
function closeAddressSuggestion(){pendingAccount=null;pendingAddressField=null;$('#addressSuggestionDialog').close()}
function productSuggestionList(context=productSearchContext){return $(context?.collection==='edit'?'#editProductSuggestions':'#productSuggestions')}
function hideProductSuggestions(){productMatches=[];activeProductMatch=-1;productSearchContext=null;$$('.product-suggestions').forEach(list=>{list.classList.add('role-hidden');list.innerHTML=''})}
function renderProductSuggestions(input,context){const query=normalizeSearch(input.value.trim());if(query.length<2){hideProductSuggestions();return}const seen=new Set();productMatches=productDirectory.filter(product=>product.searchPartNo.includes(query)).sort((a,b)=>Number(b.searchPartNo.startsWith(query))-Number(a.searchPartNo.startsWith(query))||String(a.partNo).localeCompare(String(b.partNo),'tr')).filter(product=>{const key=`${product.partNo}|${product.description}`;if(seen.has(key))return false;seen.add(key);return true}).slice(0,8);activeProductMatch=-1;productSearchContext=context;const list=productSuggestionList(context);if(!productMatches.length){hideProductSuggestions();return}list.innerHTML=productMatches.map((product,index)=>`<button type="button" role="option" data-product-suggestion-index="${index}"><strong>${escapeHtml(product.partNo)}</strong><span>${escapeHtml(product.description)}</span><small>${escapeHtml(product.source)}${product.itemNo?` · Item No: ${escapeHtml(product.itemNo)}`:''}</small></button>`).join('');const rect=input.getBoundingClientRect(),width=Math.min(window.innerWidth-20,580,Math.max(380,rect.width*2.4)),left=Math.max(10,Math.min(rect.left,window.innerWidth-width-10));list.style.left=`${left}px`;list.style.top=`${Math.max(10,Math.min(rect.bottom+4,window.innerHeight-330))}px`;list.style.width=`${width}px`;list.classList.remove('role-hidden')}
function selectProductSuggestion(product){if(!product||!productSearchContext)return;const {collection,index}=productSearchContext,target=collection==='draft'?draftOrderProducts:editOrderProducts,rowTarget=collection==='draft'?'#orderProductRows':'#editOrderProductRows';if(!target[index])return;target[index].partNo=product.partNo;target[index].description=product.description;hideProductSuggestions();if(collection==='draft')renderOrderProducts();else renderEditOrderProducts();$(`${rowTarget} input[data-${collection==='draft'?'product':'edit-product'}-index="${index}"][data-${collection==='draft'?'product':'edit-product'}-field="qty"]`)?.focus()}
function handleProductSuggestionKey(event,collection,index){if(!productSearchContext||productSearchContext.collection!==collection||productSearchContext.index!==index||!productMatches.length)return false;if(event.key==='ArrowDown'){event.preventDefault();activeProductMatch=(activeProductMatch+1)%productMatches.length}else if(event.key==='ArrowUp'){event.preventDefault();activeProductMatch=(activeProductMatch-1+productMatches.length)%productMatches.length}else if(event.key==='Enter'&&activeProductMatch>=0){event.preventDefault();selectProductSuggestion(productMatches[activeProductMatch]);return true}else if(event.key==='Escape'){event.preventDefault();hideProductSuggestions();return true}else return false;const buttons=$$(`${collection==='edit'?'#editProductSuggestions':'#productSuggestions'} button`);buttons.forEach((button,buttonIndex)=>button.classList.toggle('active',buttonIndex===activeProductMatch));buttons[activeProductMatch]?.scrollIntoView({block:'nearest'});return true}
function detailValue(value){return value===undefined||value===null||value===''?'—':escapeHtml(value)}
function detailField(label,value){return `<div class="detail-field"><span>${escapeHtml(label)}</span><strong>${detailValue(value)}</strong></div>`}
function contactDetail(title,contact={}){const fullName=[contact.firstName,contact.lastName].filter(Boolean).join(' ');return `<article class="detail-contact"><h4>${escapeHtml(title)}</h4>${detailField('Ad Soyad',fullName)}${detailField('E-posta',contact.email)}${detailField('Telefon',contact.phone)}</article>`}
function detailSetGroups(products){if(!products.length)return '<div class="empty-set-state">Set bilgisi bulunmuyor.</div>';const groups=new Map();products.forEach(product=>{const name=product.setInfo?.trim()||'Set atanmamış';if(!groups.has(name))groups.set(name,[]);groups.get(name).push(product)});return `<div class="set-groups detail-set-groups">${[...groups.entries()].map(([name,items])=>`<section class="set-group"><div class="set-group-header"><strong>${escapeHtml(name)}</strong><span>${items.length} ürün</span></div>${items.map(product=>`<div class="set-product"><b>${detailValue(product.partNo)}</b><span>${detailValue(product.description)}</span><em>${detailValue(product.qty)} adet</em></div>`).join('')}</section>`).join('')}</div>`}
function serviceVisitsDetail(visits=[]){if(!visits.length)return '<p class="detail-empty">Henüz servis kurulum kaydı girilmemiş.</p>';return `<div class="service-visit-summary">${visits.map(visit=>`<article><h4>${visit.visitNumber}. Kurulum <span>${visit.completed?'Tamamlandı':'Devam edecek'}</span></h4><div class="detail-grid">${detailField('Teknisyenler',(visit.technicians||[]).join(', '))}${detailField('Müşteri katılımcıları',(visit.customerParticipants||[]).join(', '))}${detailField('Yol süresi',`${visit.travelDuration||0} ${visit.travelUnit||'Saat'}`)}${detailField('Saha süresi',`${visit.siteDuration||0} ${visit.siteUnit||'Saat'}`)}${detailField('Check-list',visit.checklistStatus)}${detailField('Ürün durumu',visit.productStatus==='missing'?'Ürün eksik':visit.productStatus==='demo'?'Demo ürün':'Ürünler tam')}${detailField('Eksik ürünler',(visit.missingProducts||[]).join(', '))}${detailField('Demo ürün notu',visit.demoProductNote)}${detailField('Sonraki kurulum',visit.nextInstallationDate)}${detailField('Rapor paylaşıldı',visit.reportShared?'Evet':'Hayır')}${detailField('Paylaşılan e-mail',visit.sharedEmailAttachment?.name)}</div>${visit.notes?`<div class="detail-note"><span>Kurulum notu</span><p>${escapeHtml(visit.notes)}</p></div>`:''}<div class="detail-files">${(visit.attachments||[]).length?visit.attachments.map(file=>`<span>${escapeHtml(file.name)}</span>`).join(''):'<em>Kurulum raporu veya dosya eklenmemiş.</em>'}</div></article>`).join('')}</div>`}
function setDetailFullscreen(expanded){const dialog=$('#installationDetailDialog'),button=$('#toggleDetailFullscreen');dialog.classList.toggle('fullscreen-dialog',expanded);button.textContent=expanded?'🗗':'⛶';button.setAttribute('aria-label',expanded?'Tam ekrandan çık':'Tam ekran yap');button.title=expanded?'Tam ekrandan çık':'Tam ekran yap'}
function closeInstallationDetail(){setDetailFullscreen(false);$('#installationDetailDialog').close()}
function setServiceFullscreen(expanded){const dialog=$('#serviceEntryDialog'),button=$('#toggleServiceFullscreen');dialog.classList.toggle('fullscreen-dialog',expanded);button.textContent=expanded?'🗗':'⛶';button.setAttribute('aria-label',expanded?'Tam ekrandan çık':'Tam ekran yap');button.title=expanded?'Tam ekrandan çık':'Tam ekran yap'}
function openInstallationDetail(id){const item=installations.find(record=>record.id===id);if(!item)return;const isMtb=item.customerType==='mtb',contacts=item.contacts||{},shipment=item.shipment||{},products=item.orderProducts||[],attachments=item.attachments||[];$('#detailDialogTitle').textContent=item.customer||'Kurulum detayı';$('#detailDialogSubtitle').textContent=`${item.salesOrderNumber||'SO bilgisi yok'} · ${item.status||'Durum yok'}`;$('#installationDetailBody').innerHTML=`
  <section class="detail-section"><h3>Müşteri ve sipariş</h3><div class="detail-grid">${detailField('Müşteri',item.customer)}${detailField('Müşteri yapısı',isMtb?'MTB ve son kullanıcı ayrı':'Doğrudan son kullanıcı')}${isMtb?detailField('MTB firma',item.mtbName)+detailField('Son kullanıcı firma',item.endUserName):''}${detailField('Satış mühendisi',item.salesEngineer)}${detailField('SO No',item.salesOrderNumber)}${detailField('PTD No',item.ptd)}${detailField('Kurulum tutarı',Number.isFinite(Number(item.installationAmount))?new Intl.NumberFormat('tr-TR',{style:'currency',currency:'EUR'}).format(item.installationAmount):'—')}${detailField('Talep tarihi',item.requestDate)}</div></section>
  <section class="detail-section"><h3>Adresler ve kontaklar</h3><div class="detail-grid">${isMtb?detailField('Kurulum Adresi MTB',item.mtbAddress)+detailField('Kurulum Adresi Son Kullanıcı',item.endUserAddress):detailField('Kurulum adresi',item.address)}</div><div class="detail-contact-grid">${isMtb?contactDetail('MTB kontağı',contacts.mtb)+contactDetail('Son kullanıcı kontağı',contacts.endUser):contactDetail('Müşteri kontağı',contacts.customer)}</div></section>
  <section class="detail-section"><h3>Tarihler ve servis planlaması</h3><div class="detail-grid">${detailField('Tahmini sevkiyat / teslim',item.estimatedDeliveryDate)}${detailField('Tahmini kurulum',item.estimatedInstallationDate)}${detailField('Planlanan kurulum',item.date)}${detailField('Planlanan süre',item.plannedDuration?`${item.plannedDuration} ${item.plannedUnit||'Saat'}`:'—')}${detailField('Servis teknisyeni',item.tech)}${detailField('İlerleme',`%${item.progress||0}`)}</div></section>
  <section class="detail-section"><div class="detail-section-heading"><h3>Sipariş içeriği</h3><div class="detail-order-tabs"><button class="active" type="button" data-detail-order-tab="products">Ürün Listesi</button><button type="button" data-detail-order-tab="sets">Set Bilgisi</button></div></div><div id="detailProductsPanel">${products.length?`<div class="table-wrap detail-products"><table><thead><tr><th>PART NO</th><th>DESCRIPTION</th><th>QTY</th><th>SET BİLGİSİ</th></tr></thead><tbody>${products.map(product=>`<tr><td>${detailValue(product.partNo)}</td><td>${detailValue(product.description)}</td><td>${detailValue(product.qty)}</td><td>${detailValue(product.setInfo)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="detail-empty">Ürün bilgisi bulunmuyor.</p>'}</div><div id="detailSetsPanel" class="role-hidden">${detailSetGroups(products)}</div></section>
  <section class="detail-section"><h3>Sevkiyat</h3><div class="detail-grid">${detailField('Ürünler sevk edildi',shipment.productsShipped?'Evet':'Hayır')}${detailField('Sevk tarihi',shipment.shipmentDate)}${detailField('Parçalı sevkiyat',shipment.partialShipment?'Evet':'Hayır')}${detailField('Gönderilen ürünler',(shipment.shippedProducts||[]).join(', '))}</div>${shipment.demoProductNote?`<div class="detail-note"><span>Demo ürün notu</span><p>${escapeHtml(shipment.demoProductNote)}</p></div>`:''}</section>
  <section class="detail-section"><h3>Servis kurulum kayıtları</h3>${item.serviceOverrun?'<div class="service-overrun-notice">Planlanan kurulum süresi aşılmıştır.</div>':''}${serviceVisitsDetail(item.serviceVisits||[])}</section>
  <section class="detail-section"><h3>Notlar ve dosyalar</h3><div class="detail-note"><span>Notlar</span><p>${detailValue(item.notes)}</p></div><div class="detail-files">${attachments.length?attachments.map(file=>`<span>${escapeHtml(file.name)}</span>`).join(''):'<em>Dosya eklenmemiş.</em>'}</div></section>`;const canDelete=currentUser?.role==='sales'&&['draft','awaitingPlanning'].includes(item.workflowStage);$('#detailDeleteButton').classList.toggle('role-hidden',!canDelete);$('#detailDeleteButton').dataset.deleteInstallationId=canDelete?item.id:'';setDetailFullscreen(false);$('#installationDetailDialog').showModal()}
function deleteInstallation(id){const item=installations.find(record=>record.id===id);if(currentUser?.role!=='sales'||!item||!['draft','awaitingPlanning'].includes(item.workflowStage)){showToast('Bu kayıt mevcut durumunda silinemez.');return}if(!confirm(`${item.customer} · ${item.salesOrderNumber} kaydı silinsin mi?`))return;installations=installations.filter(record=>record.id!==id);localStorage.setItem('cps-installations',JSON.stringify(installations));render();if($('#installationDetailDialog').open)$('#installationDetailDialog').close();showToast('Kurulum talebi silindi.')}
function renderOrderProducts(){
  $('#orderProductRows').innerHTML=draftOrderProducts.length?draftOrderProducts.map((product,index)=>`<tr><td><input data-product-index="${index}" data-product-field="partNo" value="${escapeHtml(product.partNo)}" aria-label="Part No"></td><td><input data-product-index="${index}" data-product-field="description" value="${escapeHtml(product.description)}" aria-label="Description"></td><td><input data-product-index="${index}" data-product-field="qty" type="number" min="0.01" step="0.01" value="${escapeHtml(product.qty)}" aria-label="Qty"></td><td><input data-product-index="${index}" data-product-field="setInfo" value="${escapeHtml(product.setInfo||'')}" placeholder="Örn. Set A" aria-label="Set Bilgisi"></td><td><button class="delete-product" type="button" data-delete-product="${index}" aria-label="Ürünü sil">×</button></td></tr>`).join(''):'<tr class="empty-product-row"><td colspan="5">Henüz ürün eklenmedi. Excel yükleyin veya “Ürün ekle” düğmesini kullanın.</td></tr>';
  renderSetGroups();renderNewShipmentProducts();
}
function uniqueOrderProducts(products){const seen=new Set();return products.filter(product=>{const key=String(product.partNo||'').trim();if(!key||seen.has(key))return false;seen.add(key);return true})}
function shipmentProductMarkup(products,selected=[]){const selectedSet=new Set(selected);const valid=uniqueOrderProducts(products);return '<p>Bu sevkiyatta gönderilen ürünler</p>'+(valid.length?valid.map(product=>`<label><input name="shippedProducts" type="checkbox" value="${escapeHtml(product.partNo)}" ${selectedSet.has(product.partNo)?'checked':''}> <span><b>${escapeHtml(product.partNo)}</b> · ${escapeHtml(product.description)} <small>(${escapeHtml(product.qty)} adet)</small></span></label>`).join(''):'<div class="shipment-products-empty">Önce sipariş içeriğine ürün ekleyin.</div>')}
function renderNewShipmentProducts(){const selected=$$('#partialProductFields input[name="shippedProducts"]:checked').map(input=>input.value);$('#partialProductFields').innerHTML=shipmentProductMarkup(draftOrderProducts,selected)}
function renderEditShipmentProducts(products,selected=[]){$('#editPartialProductFields').innerHTML=shipmentProductMarkup(products,selected)}
function renderSetGroups(){
  if(!draftOrderProducts.length){$('#setGroups').innerHTML='<div class="empty-set-state">Set bilgisi göstermek için ürün ekleyin.</div>';return}
  const groups=new Map();draftOrderProducts.forEach(product=>{const setName=product.setInfo?.trim()||'Set atanmamış';if(!groups.has(setName))groups.set(setName,[]);groups.get(setName).push(product)});
  $('#setGroups').innerHTML=[...groups.entries()].map(([name,products])=>`<section class="set-group"><div class="set-group-header"><strong>${escapeHtml(name)}</strong><span>${products.length} ürün</span></div>${products.map(product=>`<div class="set-product"><b>${escapeHtml(product.partNo||'Part No bekleniyor')}</b><span>${escapeHtml(product.description||'Açıklama bekleniyor')}</span><em>${escapeHtml(product.qty||0)} adet</em></div>`).join('')}</section>`).join('');
}
function renderEditOrderProducts(){
  $('#editOrderProductRows').innerHTML=editOrderProducts.length?editOrderProducts.map((product,index)=>`<tr><td><input data-edit-product-index="${index}" data-edit-product-field="partNo" value="${escapeHtml(product.partNo)}"></td><td><input data-edit-product-index="${index}" data-edit-product-field="description" value="${escapeHtml(product.description)}"></td><td><input data-edit-product-index="${index}" data-edit-product-field="qty" type="number" min="0.01" step="0.01" value="${escapeHtml(product.qty)}"></td><td><input data-edit-product-index="${index}" data-edit-product-field="setInfo" value="${escapeHtml(product.setInfo||'')}" placeholder="Örn. Set A"></td><td><button class="delete-product" type="button" data-delete-edit-product="${index}">×</button></td></tr>`).join(''):'<tr class="empty-product-row"><td colspan="5">Henüz ürün eklenmedi.</td></tr>';renderEditSetGroups()
}
function renderEditSetGroups(){const target=$('#editSetGroups');if(!editOrderProducts.length){target.innerHTML='<div class="empty-set-state">Set bilgisi göstermek için ürün ekleyin.</div>';return}const groups=new Map();editOrderProducts.forEach(product=>{const name=product.setInfo?.trim()||'Set atanmamış';if(!groups.has(name))groups.set(name,[]);groups.get(name).push(product)});target.innerHTML=[...groups.entries()].map(([name,products])=>`<section class="set-group"><div class="set-group-header"><strong>${escapeHtml(name)}</strong><span>${products.length} ürün</span></div>${products.map(product=>`<div class="set-product"><b>${escapeHtml(product.partNo||'Part No bekleniyor')}</b><span>${escapeHtml(product.description||'Açıklama bekleniyor')}</span><em>${escapeHtml(product.qty||0)} adet</em></div>`).join('')}</section>`).join('')}
function normalizeColumnName(value){return String(value||'').toLocaleLowerCase('tr').replace(/[ıİ]/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function parseOrderWorksheet(sheet){
  const matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false});const aliases={part:['partno','partnumber'],description:['description','aciklama'],qty:['qty','quantity','adet'],set:['setbilgisi','setinfo','set']};
  const headerIndex=matrix.findIndex(row=>{const cells=row.map(normalizeColumnName);return aliases.part.some(alias=>cells.includes(alias))&&aliases.description.some(alias=>cells.includes(alias))&&aliases.qty.some(alias=>cells.includes(alias))});if(headerIndex<0)throw new Error('Part No, Description ve Qty başlıkları bulunamadı');
  const headers=matrix[headerIndex].map(normalizeColumnName);const column=names=>headers.findIndex(header=>names.includes(header));const partIndex=column(aliases.part),descriptionIndex=column(aliases.description),qtyIndex=column(aliases.qty),setIndex=column(aliases.set);const products=[];let ignored=0,blankStreak=0;
  for(const row of matrix.slice(headerIndex+1)){const partNo=String(row[partIndex]??'').trim(),description=String(row[descriptionIndex]??'').trim(),qtyText=String(row[qtyIndex]??'').trim(),setInfo=setIndex>=0?String(row[setIndex]??'').trim():'';const combined=normalizeColumnName(`${partNo} ${description}`);if(/^(total|subtotal|grandtotal|toplam|aratoplam|geneltoplam)/.test(combined)||combined.includes('grandtotal'))break;if(!partNo&&!description&&!qtyText){blankStreak++;if(products.length&&blankStreak>=2)break;continue}blankStreak=0;if(qtyText.includes('%')||partNo.includes('%')||description.includes('%')){ignored++;continue}const qty=Number(qtyText.replace(/\s/g,'').replace(',','.'));if(!partNo||!description||!Number.isFinite(qty)||qty<=0||aliases.part.includes(normalizeColumnName(partNo))){ignored++;continue}products.push({partNo,description,qty,setInfo})}
  if(!products.length)throw new Error('Geçerli ürün satırı bulunamadı');return {products,ignored}
}
async function importOrderFile(file){
  if(!file)return;if(typeof XLSX==='undefined'){showToast('Excel okuma bileşeni yüklenemedi. Sayfayı yenileyin.');return}
  try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});const result=parseOrderWorksheet(workbook.Sheets[workbook.SheetNames[0]]);draftOrderProducts.push(...result.products);renderOrderProducts();$('#orderFileStatus').textContent=`${file.name} · ${result.products.length} ürün aktarıldı${result.ignored?` · ${result.ignored} geçersiz satır atlandı`:''}`;showToast(`${result.products.length} ürün Excel dosyasından eklendi.`)}catch(error){$('#orderFileStatus').textContent=`${file.name} okunamadı`;showToast(`Excel okunamadı: ${error.message}`)}
}
async function importEditOrderFile(file){if(!file)return;if(typeof XLSX==='undefined'){showToast('Excel okuma bileşeni yüklenemedi.');return}try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});const result=parseOrderWorksheet(workbook.Sheets[workbook.SheetNames[0]]);editOrderProducts.push(...result.products);renderEditOrderProducts();$('#editOrderFileStatus').textContent=`${file.name} · ${result.products.length} ürün eklendi${result.ignored?` · ${result.ignored} satır atlandı`:''}`}catch(error){showToast(`Excel okunamadı: ${error.message}`)}}
function render(){
  const term=($('#searchInput')?.value||'').toLocaleLowerCase('tr');
  const filter=$('#statusFilter')?.value||'';
  const year=$('#yearFilter')?.value||'',quarter=$('#quarterFilter')?.value||'',sales=$('#salesFilter')?.value||'',customer=$('#customerFilter')?.value||'';
  const visibleInstallations=currentUser?.role==='supervisor'?installations.filter(item=>item.workflowStage!=='draft'):installations;
  const filtered=visibleInstallations.filter(x=>{const date=recordDate(x),recordQuarter=date?Math.floor(date.getMonth()/3)+1:null;return (!filter||x.status===filter)&&(!year||date?.getFullYear()===Number(year))&&(!quarter||recordQuarter===Number(quarter))&&(!sales||x.salesEngineer===sales)&&(!customer||x.customer===customer)&&(`${x.customer} ${x.salesOrderNumber} ${x.ptd} ${x.salesEngineer}`.toLocaleLowerCase('tr').includes(term))});
  $('#installationRows').innerHTML=visibleInstallations.slice(0,4).map(rowTemplate).join('');
  $('#allInstallationRows').innerHTML=filtered.map(installationRowTemplate).join('') || '<tr><td colspan="9">Aramanızla eşleşen kayıt bulunamadı.</td></tr>';
  $('#activeCount').textContent=visibleInstallations.length;
  $('#navCount').textContent=visibleInstallations.length;
  $('#overrunCount').textContent=visibleInstallations.filter(x=>x.status==='Süre aşıldı').length;
  $('#attentionCount').textContent=visibleInstallations.filter(x=>['Süre aşıldı','Sevkiyat bekliyor'].includes(x.status)).length;
  updateFilterCount();
}

function showView(name){
  $$('.view').forEach(v=>v.classList.remove('active-view'));
  $$('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name));
  const direct=$(`#${name}View`);
  if(direct) direct.classList.add('active-view'); else {$('#placeholderView').classList.add('active-view');$('#placeholderTitle').textContent=$(`.nav-item[data-view="${name}"]`)?.textContent.trim()||'Bu bölüm hazırlanıyor'}
  $('.sidebar')?.classList.remove('open');
}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function setConditionalSection(selector,active){const section=$(selector);if(!section)return;section.classList.toggle('role-hidden',!active);section.querySelectorAll('input,select,textarea').forEach(field=>{field.disabled=!active;if(field.dataset.required!==undefined)field.required=active})}
function updateCustomerFields(){const isMtb=$('#customerType').value==='mtb';setConditionalSection('#mtbCompanyFields',isMtb);setConditionalSection('#splitContactFields',isMtb);setConditionalSection('#splitAddressFields',isMtb);setConditionalSection('#directContactFields',!isMtb);setConditionalSection('#directAddressField',!isMtb);hideAccountSuggestions()}
function updateShipmentFields(){const shipped=$('#productsShipped').checked;setConditionalSection('#shipmentFields',shipped);if(!shipped)$('#partialShipment').checked=false;updatePartialShipmentFields()}
function updatePartialShipmentFields(){const partial=$('#productsShipped').checked&&$('#partialShipment').checked;setConditionalSection('#partialProductFields',partial)}
function updateEditShipmentFields(){const shipped=$('#editProductsShipped').checked;setConditionalSection('#editShipmentFields',shipped);if(!shipped)$('#editPartialShipment').checked=false;updateEditPartialShipmentFields()}
function updateEditPartialShipmentFields(){const partial=$('#editProductsShipped').checked&&$('#editPartialShipment').checked;setConditionalSection('#editPartialProductFields',partial)}
function validateEstimatedDates(){const delivery=$('#estimatedDeliveryDate'),installation=$('#estimatedInstallationDate');installation.min=delivery.value||'';const invalid=Boolean(delivery.value&&installation.value&&installation.value<delivery.value);installation.setCustomValidity(invalid?'Tahmini kurulum tarihi, tahmini sevkiyat tarihinden önce olamaz.':'');return !invalid}
function setFormValue(form,name,value){if(form.elements[name])form.elements[name].value=value??''}
function openNew(){
  if(!['admin','sales'].includes(currentUser?.role)){showToast('Yeni kurulum kaydını yalnızca Satış Mühendisi oluşturabilir.');return}
  if(!navigator.onLine){showToast('İşleme devam etmek için online olun.');return}
  editingInstallationId=null;const form=$('#installationForm');form.reset();draftOrderProducts=[];$('#installationDialogEyebrow').textContent='YENİ KAYIT';$('#installationDialogTitle').textContent='Yeni kurulum oluştur';$('#saveInstallation').textContent='Taslağı kaydet';$('#orderFileStatus').textContent='Excel sütunları: Part No, Description, Qty; opsiyonel: Set Bilgisi';
  const salesEngineer=$('[name="salesEngineer"]');if(currentUser?.role==='sales'&&[...salesEngineer.options].some(option=>option.value===currentUser.name))salesEngineer.value=currentUser.name;
  updateCustomerFields();updateShipmentFields();validateEstimatedDates();renderOrderProducts();$('#installationDialog').showModal()
}
function openFullEdit(id){
  if(currentUser?.role!=='sales'){showToast('Kurulum talebini yalnızca Satış Mühendisi düzenleyebilir.');return}if(!navigator.onLine){showToast('İşleme devam etmek için online olun.');return}const item=installations.find(record=>record.id===id);if(!item)return;
  editingInstallationId=id;const form=$('#installationForm');form.reset();$('#installationDialogEyebrow').textContent=item.workflowStage==='draft'?'TASLAK':'SATIŞ KAYDI';$('#installationDialogTitle').textContent='Kurulum talebini düzenle';$('#saveInstallation').textContent='Değişiklikleri kaydet';
  setFormValue(form,'customer',item.customer);setFormValue(form,'customerType',item.customerType||'direct');updateCustomerFields();setFormValue(form,'mtbName',item.mtbName);setFormValue(form,'endUserName',item.endUserName);setFormValue(form,'salesEngineer',item.salesEngineer);setFormValue(form,'salesOrderNumber',item.salesOrderNumber);setFormValue(form,'ptd',item.ptd==='—'?'':item.ptd);setFormValue(form,'amount',item.installationAmount);setFormValue(form,'address',item.address);setFormValue(form,'mtbAddress',item.mtbAddress);setFormValue(form,'endUserAddress',item.endUserAddress||item.address);
  const contacts=item.contacts||{};setFormValue(form,'contactFirstName',contacts.customer?.firstName);setFormValue(form,'contactLastName',contacts.customer?.lastName);setFormValue(form,'contactEmail',contacts.customer?.email);setFormValue(form,'contactPhone',contacts.customer?.phone);setFormValue(form,'mtbContactFirstName',contacts.mtb?.firstName);setFormValue(form,'mtbContactLastName',contacts.mtb?.lastName);setFormValue(form,'mtbContactEmail',contacts.mtb?.email);setFormValue(form,'mtbContactPhone',contacts.mtb?.phone);setFormValue(form,'endUserContactFirstName',contacts.endUser?.firstName);setFormValue(form,'endUserContactLastName',contacts.endUser?.lastName);setFormValue(form,'endUserContactEmail',contacts.endUser?.email);setFormValue(form,'endUserContactPhone',contacts.endUser?.phone);
  setFormValue(form,'estimatedDeliveryDate',item.estimatedDeliveryDate);setFormValue(form,'estimatedInstallationDate',item.estimatedInstallationDate);setFormValue(form,'notes',item.notes);draftOrderProducts=(item.orderProducts||[]).map(product=>({...product}));renderOrderProducts();const shipment=item.shipment||{};$('#productsShipped').checked=Boolean(shipment.productsShipped);$('#partialShipment').checked=Boolean(shipment.partialShipment);updateShipmentFields();setFormValue(form,'shipmentDate',shipment.shipmentDate);setFormValue(form,'demoProductNote',shipment.demoProductNote);$$('#partialProductFields input[name="shippedProducts"]').forEach(input=>input.checked=(shipment.shippedProducts||[]).includes(input.value));validateEstimatedDates();$('#orderFileStatus').textContent=`${draftOrderProducts.length} kayıtlı ürün düzenleniyor`;$('#installationDialog').showModal()
}
function sendToPlanning(id){if(currentUser?.role!=='sales'){showToast('Bu işlemi yalnızca Satış Mühendisi yapabilir.');return}if(!navigator.onLine){showToast('İşleme devam etmek için online olun.');return}const item=installations.find(record=>record.id===id);if(!item||item.workflowStage!=='draft')return;const sentAt=new Date();item.workflowStage='awaitingPlanning';item.status='Planlama bekliyor';item.date='Planlama bekliyor';item.requestDateIso=sentAt.toISOString().slice(0,10);item.requestDate=new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',year:'numeric'}).format(sentAt);item.sentToPlanningAt=sentAt.toISOString();localStorage.setItem('cps-installations',JSON.stringify(installations));render();showToast('Kurulum Servis Supervisor planlama kuyruğuna gönderildi.')}
function durationAsHours(value,unit){return Number(value||0)*(unit==='Gün'?8:1)}
function serviceProductChecklist(item,selected=[]){const selectedSet=new Set(selected);const products=uniqueOrderProducts(item.orderProducts||[]);return '<p>Eksik ürünleri işaretleyin</p>'+(products.length?products.map(product=>`<label><input name="missingProducts" type="checkbox" value="${escapeHtml(product.partNo)}" ${selectedSet.has(product.partNo)?'checked':''}><span><b>${escapeHtml(product.partNo)}</b> · ${escapeHtml(product.description)}</span></label>`).join(''):'<div class="shipment-products-empty">Sipariş ürün bilgisi bulunmuyor.</div>')}
function updateServiceFields(){const missing=$('#serviceProductStatus').value==='missing';setConditionalSection('#missingProductFields',missing);const completed=$('#installationCompleted').checked;setConditionalSection('#nextInstallationDateField',!completed);setConditionalSection('#sharedEmailField',$('#reportShared').checked)}
function renderServiceVisitTabs(item,activeIndex){const visits=item.serviceVisits||[],allowNext=!visits.length||!visits.at(-1)?.completed;const count=visits.length+(allowNext?1:0);$('#serviceVisitTabs').innerHTML=Array.from({length:count},(_,index)=>`<button class="${index===activeIndex?'active':''}" type="button" data-service-visit-index="${index}">${index+1}. Kurulum${index<visits.length?'<small>Kaydedildi</small>':'<small>Yeni</small>'}</button>`).join('')}
function loadServiceVisit(item,index){const visit=(item.serviceVisits||[])[index]||{},form=$('#serviceEntryForm'),defaultTechnician=item.tech&&item.tech!=='Atama bekliyor'?item.tech:currentUser?.role==='technician'?currentUser.name:'';form.reset();$('#serviceInstallationId').value=item.id;$('#serviceVisitIndex').value=index;$('#serviceRecordTitle').textContent=`${item.customer} · ${item.salesOrderNumber}`;$('#servicePlannedDate').value=item.plannedDateIso||item.date||'—';$('#servicePlannedDuration').value=item.plannedDuration?`${item.plannedDuration} ${item.plannedUnit||'Saat'}`:'—';form.elements.productStatus.value=visit.productStatus||'complete';form.elements.demoProductNote.value=visit.demoProductNote||'';form.elements.checklistStatus.value=visit.checklistStatus||'';form.elements.technicians.value=(visit.technicians||[defaultTechnician]).filter(Boolean).join('\n');form.elements.customerParticipants.value=(visit.customerParticipants||[]).join('\n');form.elements.travelDuration.value=visit.travelDuration??0;form.elements.travelUnit.value=visit.travelUnit||'Saat';form.elements.siteDuration.value=visit.siteDuration??0;form.elements.siteUnit.value=visit.siteUnit||'Saat';form.elements.serviceNotes.value=visit.notes||'';$('#installationCompleted').checked=Boolean(visit.completed);form.elements.nextInstallationDate.value=visit.nextInstallationDate||'';$('#reportShared').checked=Boolean(visit.reportShared);$('#missingProductChecklist').innerHTML=serviceProductChecklist(item,visit.missingProducts||[]);updateServiceFields();$('#serviceOverrunNotice').classList.toggle('role-hidden',!item.serviceOverrun);renderServiceVisitTabs(item,index)}
function openServiceEntry(id){if(!['supervisor','technician'].includes(currentUser?.role)){showToast('Bu işlem için servis yetkisi gerekir.');return}if(!navigator.onLine){showToast('İşleme devam etmek için online olun.');return}const item=installations.find(record=>record.id===id);if(!item)return;const visits=item.serviceVisits||[],index=visits.length&&visits.at(-1).completed?visits.length-1:visits.length;loadServiceVisit(item,index);setServiceFullscreen(false);$('#serviceEntryDialog').showModal()}
function openPlanning(id){
  if(currentUser?.role!=='supervisor'){showToast('Servis planlamasını yalnızca Servis Supervisor düzenleyebilir.');return}
  if(!navigator.onLine){showToast('İşleme devam etmek için online olun.');return}
  const item=installations.find(record=>record.id===id);if(!item)return;
  $('#planningInstallationId').value=item.id;$('#planningRecordTitle').textContent=`${item.customer} · ${item.salesOrderNumber}`;
  const form=$('#planningForm');form.elements.plannedDate.value=item.plannedDateIso||'';form.elements.plannedDuration.value=item.plannedDuration||8;form.elements.plannedUnit.value=item.plannedUnit||'Saat';form.elements.technician.value=item.tech==='Atama bekliyor'?'':item.tech;
  $('#planningDialog').showModal();
}
function openShipment(id){
  if(currentUser?.role!=='sales'){showToast('Sevkiyat bilgisini yalnızca Satış Mühendisi düzenleyebilir.');return}
  if(!navigator.onLine){showToast('İşleme devam etmek için online olun.');return}
  const item=installations.find(record=>record.id===id);if(!item)return;const shipment=item.shipment||{};const form=$('#shipmentForm');
  $('#shipmentInstallationId').value=item.id;$('#shipmentRecordTitle').textContent=`${item.customer} · ${item.salesOrderNumber}`;$('#editProductsShipped').checked=Boolean(shipment.productsShipped);$('#editPartialShipment').checked=Boolean(shipment.partialShipment);form.elements.shipmentDate.value=shipment.shipmentDate||'';form.elements.demoProductNote.value=shipment.demoProductNote||'';
  renderEditShipmentProducts(item.orderProducts||[],shipment.shippedProducts||[]);updateEditShipmentFields();$('#shipmentDialog').showModal();
}
function openOrderEdit(id){if(currentUser?.role!=='sales'){showToast('Sipariş ürünlerini yalnızca Satış Mühendisi düzenleyebilir.');return}if(!navigator.onLine){showToast('İşleme devam etmek için online olun.');return}const item=installations.find(record=>record.id===id);if(!item)return;editOrderProducts=(item.orderProducts||[]).map(product=>({...product}));$('#orderEditInstallationId').value=item.id;$('#orderEditRecordTitle').textContent=`${item.customer} · ${item.salesOrderNumber}`;$('#editOrderFileStatus').textContent='Mevcut satırları düzenleyebilir veya yeni ürün ekleyebilirsiniz.';renderEditOrderProducts();$('#orderEditDialog').showModal()}
function toggleLanguage(){language=language==='tr'?'en':'tr';document.documentElement.lang=language;$$('[data-i18n]').forEach(node=>node.textContent=translations[language][node.dataset.i18n]);$('#languageButton').textContent=language.toUpperCase();$('#loginLanguage').textContent=language==='tr'?'EN':'TR';showToast(language==='tr'?'Dil Türkçe olarak değiştirildi.':'Language changed to English.')}
function applyUser(user){
  currentUser=user;
  $('#currentUserInitials').textContent=user.initials;
  $('#currentUserName').textContent=user.name;
  $('#currentUserRole').textContent=user.roleLabel;
  $('#welcomeHeading').textContent=`Günaydın, ${user.firstName}`;
  $('#welcomeDescription').textContent=user.description;
  $$('[data-roles]').forEach(item=>item.classList.toggle('role-hidden',!item.dataset.roles.split(',').includes(user.role)));
  $$('.sales-action').forEach(item=>item.classList.toggle('role-hidden',!['admin','sales'].includes(user.role)));
  showView('dashboard');render();
}

$('#loginForm').addEventListener('submit',event=>{
  event.preventDefault();
  const user=userDirectory.find(item=>item.username===$('#username').value.trim().toLocaleLowerCase('tr-TR')&&item.password===$('#password').value);
  if(user){
    sessionStorage.setItem('cps-session',user.username);$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');applyUser(user);
  }else $('#loginError').textContent='Kullanıcı adı veya şifre hatalı.';
});
$('#quickLoginAccounts').addEventListener('click',event=>{const button=event.target.closest('[data-quick-login]');if(!button)return;const user=userDirectory.find(item=>item.username===button.dataset.quickLogin);if(!user)return;$('#username').value=user.username;$('#password').value=user.password;$('#loginError').textContent='';$('#loginForm').requestSubmit()});
$('#logoutButton').addEventListener('click',()=>{sessionStorage.removeItem('cps-session');currentUser=null;$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#password').value=''});
$('#mainNav').addEventListener('click',event=>{const button=event.target.closest('[data-view]');if(button)showView(button.dataset.view)});
$('#newInstallationButton').addEventListener('click',openNew);$$('.open-new').forEach(x=>x.addEventListener('click',openNew));
$('#showAllButton').addEventListener('click',()=>showView('installations'));
$('#languageButton').addEventListener('click',toggleLanguage);$('#loginLanguage').addEventListener('click',toggleLanguage);
$('#searchInput').addEventListener('input',render);$('#statusFilter').addEventListener('change',event=>{$('#advancedStatusFilter').value=event.target.value;render()});
$('#toggleAdvancedFilters').addEventListener('click',()=>{const panel=$('#advancedFilterPanel'),open=panel.classList.toggle('role-hidden')===false;$('#toggleAdvancedFilters').setAttribute('aria-expanded',String(open))});
$('#closeAdvancedFilters').addEventListener('click',()=>{$('#advancedFilterPanel').classList.add('role-hidden');$('#toggleAdvancedFilters').setAttribute('aria-expanded','false')});
$('#advancedStatusFilter').addEventListener('change',event=>{$('#statusFilter').value=event.target.value});
$('#applyAdvancedFilters').addEventListener('click',()=>{render();$('#advancedFilterPanel').classList.add('role-hidden');$('#toggleAdvancedFilters').setAttribute('aria-expanded','false')});
$('#clearAdvancedFilters').addEventListener('click',()=>{['yearFilter','quarterFilter','salesFilter','customerFilter','statusFilter','advancedStatusFilter'].forEach(id=>$(`#${id}`).value='');render()});
$('#importOrderButton').addEventListener('click',()=>$('#orderFileInput').click());$('#orderFileInput').addEventListener('change',event=>{importOrderFile(event.target.files[0]);event.target.value=''});$('#addOrderProductButton').addEventListener('click',()=>{draftOrderProducts.push({partNo:'',description:'',qty:1,setInfo:''});renderOrderProducts();$('#orderProductRows input')?.focus()});
$('#editImportOrderButton').addEventListener('click',()=>$('#editOrderFileInput').click());$('#editOrderFileInput').addEventListener('change',event=>{importEditOrderFile(event.target.files[0]);event.target.value=''});$('#editAddOrderProductButton').addEventListener('click',()=>{editOrderProducts.push({partNo:'',description:'',qty:1,setInfo:''});renderEditOrderProducts()});
$('#orderProductRows').addEventListener('input',event=>{const input=event.target.closest('[data-product-field]');if(!input)return;const index=Number(input.dataset.productIndex),product=draftOrderProducts[index];product[input.dataset.productField]=input.dataset.productField==='qty'?Number(input.value):input.value;if(input.dataset.productField==='partNo')renderProductSuggestions(input,{collection:'draft',index});else hideProductSuggestions();renderSetGroups()});
$('#orderProductRows').addEventListener('click',event=>{const button=event.target.closest('[data-delete-product]');if(!button)return;draftOrderProducts.splice(Number(button.dataset.deleteProduct),1);renderOrderProducts()});
$('#orderProductRows').addEventListener('keydown',event=>{const input=event.target.closest('[data-product-field]');if(!input)return;const index=Number(input.dataset.productIndex);if(handleProductSuggestionKey(event,'draft',index))return;if(event.key!=='Enter')return;event.preventDefault();hideProductSuggestions();if(index===draftOrderProducts.length-1){draftOrderProducts.push({partNo:'',description:'',qty:1,setInfo:''});renderOrderProducts();$(`#orderProductRows input[data-product-index="${index+1}"][data-product-field="partNo"]`)?.focus()}else $(`#orderProductRows input[data-product-index="${index+1}"][data-product-field="partNo"]`)?.focus()});
$$('[data-order-tab]').forEach(button=>button.addEventListener('click',()=>{$$('[data-order-tab]').forEach(tab=>tab.classList.toggle('active',tab===button));$('#productsTabPanel').classList.toggle('role-hidden',button.dataset.orderTab!=='products');$('#setsTabPanel').classList.toggle('role-hidden',button.dataset.orderTab!=='sets');if(button.dataset.orderTab==='sets')renderSetGroups()}));
$('#editOrderProductRows').addEventListener('input',event=>{const input=event.target.closest('[data-edit-product-field]');if(!input)return;const index=Number(input.dataset.editProductIndex),product=editOrderProducts[index];product[input.dataset.editProductField]=input.dataset.editProductField==='qty'?Number(input.value):input.value;if(input.dataset.editProductField==='partNo')renderProductSuggestions(input,{collection:'edit',index});else hideProductSuggestions();renderEditSetGroups()});$('#editOrderProductRows').addEventListener('keydown',event=>{const input=event.target.closest('[data-edit-product-field]');if(input)handleProductSuggestionKey(event,'edit',Number(input.dataset.editProductIndex))});$('#editOrderProductRows').addEventListener('click',event=>{const button=event.target.closest('[data-delete-edit-product]');if(!button)return;hideProductSuggestions();editOrderProducts.splice(Number(button.dataset.deleteEditProduct),1);renderEditOrderProducts()});
$$('[data-edit-order-tab]').forEach(button=>button.addEventListener('click',()=>{$$('[data-edit-order-tab]').forEach(tab=>tab.classList.toggle('active',tab===button));$('#editProductsTabPanel').classList.toggle('role-hidden',button.dataset.editOrderTab!=='products');$('#editSetsTabPanel').classList.toggle('role-hidden',button.dataset.editOrderTab!=='sets');if(button.dataset.editOrderTab==='sets')renderEditSetGroups()}));
$('#customerType').addEventListener('change',updateCustomerFields);$('#productsShipped').addEventListener('change',updateShipmentFields);$('#partialShipment').addEventListener('change',updatePartialShipmentFields);$('#editProductsShipped').addEventListener('change',updateEditShipmentFields);$('#editPartialShipment').addEventListener('change',updateEditPartialShipmentFields);$('#estimatedDeliveryDate').addEventListener('change',validateEstimatedDates);$('#estimatedInstallationDate').addEventListener('change',validateEstimatedDates);
$('#serviceProductStatus').addEventListener('change',updateServiceFields);$('#installationCompleted').addEventListener('change',updateServiceFields);$('#reportShared').addEventListener('change',updateServiceFields);$('#serviceVisitTabs').addEventListener('click',event=>{const button=event.target.closest('[data-service-visit-index]');if(!button)return;const item=installations.find(record=>record.id===Number($('#serviceInstallationId').value));if(item)loadServiceVisit(item,Number(button.dataset.serviceVisitIndex))});
accountSearchConfigs.forEach(config=>{const input=$(config.input),list=$(config.list);input.addEventListener('input',event=>renderAccountSuggestions(event.target.value,config));input.addEventListener('keydown',event=>{if(activeAccountSearch!==config||!accountMatches.length)return;if(event.key==='ArrowDown'){event.preventDefault();activeAccountMatch=(activeAccountMatch+1)%accountMatches.length}else if(event.key==='ArrowUp'){event.preventDefault();activeAccountMatch=(activeAccountMatch-1+accountMatches.length)%accountMatches.length}else if(event.key==='Enter'&&activeAccountMatch>=0){event.preventDefault();selectAccount(accountMatches[activeAccountMatch],config);return}else if(event.key==='Escape'){hideAccountSuggestions(config);return}else return;$$(`${config.list} button`).forEach((button,index)=>button.classList.toggle('active',index===activeAccountMatch));$$(`${config.list} button`)[activeAccountMatch]?.scrollIntoView({block:'nearest'})});input.addEventListener('blur',()=>setTimeout(()=>hideAccountSuggestions(config),150));list.addEventListener('mousedown',event=>{const button=event.target.closest('[data-account-index]');if(!button)return;event.preventDefault();selectAccount(accountMatches[Number(button.dataset.accountIndex)],config)})});
$('#useSuggestedAddress').addEventListener('click',()=>{const field=pendingAddressField;if(pendingAccount&&field)$(`[name="${field}"]`).value=pendingAccount.address||'';closeAddressSuggestion();if(field)$(`[name="${field}"]`).focus()});
$('#useNewAddress').addEventListener('click',()=>{const field=pendingAddressField;if(field)$(`[name="${field}"]`).value='';closeAddressSuggestion();if(field)$(`[name="${field}"]`).focus()});
$('#closeAddressSuggestion').addEventListener('click',closeAddressSuggestion);
$('#closeInstallationDetail').addEventListener('click',closeInstallationDetail);$('#detailCloseButton').addEventListener('click',closeInstallationDetail);$('#installationDetailDialog').addEventListener('close',()=>setDetailFullscreen(false));$('#detailDeleteButton').addEventListener('click',event=>deleteInstallation(Number(event.currentTarget.dataset.deleteInstallationId)));
$('#toggleDetailFullscreen').addEventListener('click',()=>setDetailFullscreen(!$('#installationDetailDialog').classList.contains('fullscreen-dialog')));$('#installationDetailBody').addEventListener('click',event=>{const button=event.target.closest('[data-detail-order-tab]');if(!button)return;const showSets=button.dataset.detailOrderTab==='sets';$$('[data-detail-order-tab]').forEach(tab=>tab.classList.toggle('active',tab===button));$('#detailProductsPanel').classList.toggle('role-hidden',showSets);$('#detailSetsPanel').classList.toggle('role-hidden',!showSets)});
$('#toggleServiceFullscreen').addEventListener('click',()=>setServiceFullscreen(!$('#serviceEntryDialog').classList.contains('fullscreen-dialog')));$('#serviceEntryDialog').addEventListener('close',()=>setServiceFullscreen(false));
$$('.product-suggestions').forEach(list=>list.addEventListener('mousedown',event=>{const button=event.target.closest('[data-product-suggestion-index]');if(!button)return;event.preventDefault();selectProductSuggestion(productMatches[Number(button.dataset.productSuggestionIndex)])}));$('#orderProductRows').addEventListener('focusout',()=>setTimeout(hideProductSuggestions,150));$('#editOrderProductRows').addEventListener('focusout',()=>setTimeout(hideProductSuggestions,150));
$('#toggleInstallationFullscreen').addEventListener('click',()=>{const dialog=$('#installationDialog');const expanded=dialog.classList.toggle('fullscreen-dialog');const button=$('#toggleInstallationFullscreen');button.textContent=expanded?'🗗':'⛶';button.setAttribute('aria-label',expanded?'Tam ekrandan çık':'Tam ekran yap');button.title=expanded?'Tam ekrandan çık':'Tam ekran yap'});
$('#allInstallationRows').addEventListener('click',event=>{const serviceButton=event.target.closest('[data-service-entry-id]');if(serviceButton){openServiceEntry(Number(serviceButton.dataset.serviceEntryId));return}const deleteButton=event.target.closest('[data-delete-installation-id]');if(deleteButton){deleteInstallation(Number(deleteButton.dataset.deleteInstallationId));return}const detailButton=event.target.closest('[data-record-detail-id]');if(detailButton){openInstallationDetail(Number(detailButton.dataset.recordDetailId));return}const editButton=event.target.closest('[data-record-edit-id]');if(editButton){openFullEdit(Number(editButton.dataset.recordEditId));return}const sendButton=event.target.closest('[data-send-planning-id]');if(sendButton){sendToPlanning(Number(sendButton.dataset.sendPlanningId));return}const actionButton=event.target.closest('[data-installation-id]');if(actionButton){const id=Number(actionButton.dataset.installationId);if(currentUser?.role==='supervisor')openPlanning(id);else if(currentUser?.role==='sales')openShipment(id);return}const row=event.target.closest('[data-record-id]');if(row)openInstallationDetail(Number(row.dataset.recordId))});
$('#allInstallationRows').addEventListener('keydown',event=>{if(!['Enter',' '].includes(event.key)||event.target.closest('button'))return;const row=event.target.closest('[data-record-id]');if(row){event.preventDefault();openInstallationDetail(Number(row.dataset.recordId))}});
$('#installationForm').addEventListener('submit',event=>{
  if(event.submitter?.value==='cancel')return;
  event.preventDefault();
  if(!navigator.onLine){$('#installationDialog').close();showToast('İşleme devam etmek için online olun.');return}
  if(!validateEstimatedDates()){$('#estimatedInstallationDate').reportValidity();return}
  const data=new FormData(event.currentTarget);
  if(!draftOrderProducts.length){showToast('Sipariş içeriğine en az bir ürün eklenmelidir.');return}
  const invalidProduct=draftOrderProducts.find(product=>!product.partNo.trim()||!product.description.trim()||!Number(product.qty));if(invalidProduct){showToast('Her ürün için Part No, Description ve Qty bilgileri zorunludur.');return}
  const partialShipment=data.get('partialShipment')==='on';const shippedProducts=data.getAll('shippedProducts');
  if(partialShipment&&!shippedProducts.length){showToast('Parçalı sevkiyatta gönderilen en az bir ürün seçilmelidir.');return}
  const attachments=[...event.currentTarget.elements.attachments.files].map(file=>({name:file.name,size:file.size,type:file.type}));
  const customerType=data.get('customerType');
  const contacts=customerType==='mtb'?{mtb:{firstName:data.get('mtbContactFirstName'),lastName:data.get('mtbContactLastName'),email:data.get('mtbContactEmail'),phone:data.get('mtbContactPhone')},endUser:{firstName:data.get('endUserContactFirstName'),lastName:data.get('endUserContactLastName'),email:data.get('endUserContactEmail'),phone:data.get('endUserContactPhone')}}:{customer:{firstName:data.get('contactFirstName'),lastName:data.get('contactLastName'),email:data.get('contactEmail'),phone:data.get('contactPhone')}};
  const editable={customer:data.get('customer'),customerType,mtbName:data.get('mtbName')||'',endUserName:data.get('endUserName')||'',contacts,address:data.get('address')||'',mtbAddress:data.get('mtbAddress')||'',endUserAddress:data.get('endUserAddress')||'',salesOrderNumber:data.get('salesOrderNumber'),salesEngineer:data.get('salesEngineer'),ptd:data.get('ptd')||'—',installationAmount:Number(data.get('amount')),orderProducts:draftOrderProducts.map(product=>({...product})),estimatedDeliveryDate:data.get('estimatedDeliveryDate')||null,estimatedInstallationDate:data.get('estimatedInstallationDate')||null,notes:data.get('notes')||'',shipment:{productsShipped:data.get('productsShipped')==='on',shipmentDate:data.get('shipmentDate')||null,partialShipment,shippedProducts,demoProductNote:data.get('demoProductNote')||''}};
  let successMessage;
  if(editingInstallationId){const item=installations.find(record=>record.id===editingInstallationId);if(!item)return;Object.assign(item,editable);if(attachments.length)item.attachments=[...(item.attachments||[]),...attachments];successMessage='Kurulum talebi güncellendi.'}
  else{installations.unshift({id:Date.now(),...editable,attachments,requestDateIso:null,requestDate:'—',workflowStage:'draft',status:'Taslak',date:'—',tech:'Atama bekliyor',initials:'?',plannedDuration:null,plannedUnit:'Saat',progress:0,createdBy:currentUser.username,createdAt:new Date().toISOString()});successMessage='Yeni kurulum taslak olarak kaydedildi.'}
  localStorage.setItem('cps-installations',JSON.stringify(installations));render();editingInstallationId=null;event.currentTarget.reset();draftOrderProducts=[];renderOrderProducts();$('#orderFileStatus').textContent='Excel sütunları: Part No, Description, Qty; opsiyonel: Set Bilgisi';updateCustomerFields();updateShipmentFields();$('#installationDialog').close();showToast(successMessage);
});
$('#planningForm').addEventListener('submit',event=>{
  if(event.submitter?.value==='cancel')return;
  event.preventDefault();
  if(currentUser?.role!=='supervisor'){showToast('Bu işlem için Servis Supervisor yetkisi gerekir.');return}
  const data=new FormData(event.currentTarget);const item=installations.find(record=>record.id===Number(data.get('installationId')));if(!item)return;
  const plannedDateIso=data.get('plannedDate');const plannedDate=new Date(`${plannedDateIso}T12:00:00`);const technician=data.get('technician');
  item.plannedDateIso=plannedDateIso;item.date=new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',year:'numeric'}).format(plannedDate);item.plannedDuration=Number(data.get('plannedDuration'));item.plannedUnit=data.get('plannedUnit');item.tech=technician;item.initials=technician.split(' ').map(part=>part[0]).join('');item.workflowStage='planned';item.status='Planlandı';item.progress=Math.max(item.progress,15);
  localStorage.setItem('cps-installations',JSON.stringify(installations));render();$('#planningDialog').close();showToast('Servis planlaması kaydedildi.');
});
$('#serviceEntryForm').addEventListener('submit',event=>{
  if(event.submitter?.value==='cancel')return;event.preventDefault();if(!['supervisor','technician'].includes(currentUser?.role)){showToast('Bu işlem için servis yetkisi gerekir.');return}if(!navigator.onLine){showToast('İşleme devam etmek için online olun.');return}
  const form=event.currentTarget,data=new FormData(form),item=installations.find(record=>record.id===Number(data.get('installationId')));if(!item)return;const index=Number(data.get('visitIndex')),visits=item.serviceVisits||[],existing=visits[index]||{};const missingProducts=data.getAll('missingProducts');if(data.get('productStatus')==='missing'&&!missingProducts.length){showToast('Eksik olan en az bir ürün seçilmelidir.');return}
  const completed=data.get('completed')==='on';if(!completed&&!data.get('nextInstallationDate')){showToast('Kurulum tamamlanmadıysa sonraki kurulum tarihi zorunludur.');form.elements.nextInstallationDate.focus();return}const reportShared=data.get('reportShared')==='on',sharedFile=form.elements.sharedEmailAttachment.files[0];if(reportShared&&!sharedFile&&!existing.sharedEmailAttachment){showToast('Müşteri ile paylaşılan e-mail dosyası eklenmelidir.');return}
  const travelDuration=Number(data.get('travelDuration')),siteDuration=Number(data.get('siteDuration')),travelUnit=data.get('travelUnit'),siteUnit=data.get('siteUnit');const priorHours=visits.reduce((total,visit,visitIndex)=>visitIndex===index?total:total+durationAsHours(visit.travelDuration,visit.travelUnit)+durationAsHours(visit.siteDuration,visit.siteUnit),0),projectedHours=priorHours+durationAsHours(travelDuration,travelUnit)+durationAsHours(siteDuration,siteUnit),plannedHours=durationAsHours(item.plannedDuration,item.plannedUnit);if(plannedHours&&projectedHours>plannedHours&&!item.serviceOverrun&&!confirm('Planlanan kurulum saati aşıldı, devam etmek istiyor musunuz?'))return;
  const newAttachments=[...form.elements.serviceAttachments.files].map(file=>({name:file.name,size:file.size,type:file.type,addedAt:new Date().toISOString()}));const visit={...existing,visitNumber:index+1,productStatus:data.get('productStatus'),missingProducts,demoProductNote:data.get('demoProductNote')||'',checklistStatus:data.get('checklistStatus'),technicians:String(data.get('technicians')).split(/\r?\n/).map(value=>value.trim()).filter(Boolean),customerParticipants:String(data.get('customerParticipants')).split(/\r?\n/).map(value=>value.trim()).filter(Boolean),travelDuration,travelUnit,siteDuration,siteUnit,attachments:[...(existing.attachments||[]),...newAttachments],notes:data.get('serviceNotes')||'',completed,nextInstallationDate:completed?null:data.get('nextInstallationDate'),reportShared,sharedEmailAttachment:sharedFile?{name:sharedFile.name,size:sharedFile.size,type:sharedFile.type}:existing.sharedEmailAttachment||null,updatedBy:currentUser.name,updatedAt:new Date().toISOString()};if(index<visits.length)visits[index]=visit;else visits.push(visit);item.serviceVisits=visits;item.actualInstallationHours=projectedHours;item.serviceOverrun=Boolean(plannedHours&&projectedHours>plannedHours);item.workflowStage=completed?'completed':'inService';item.status=item.serviceOverrun?'Süre aşıldı':completed?'Tamamlandı':'Devam ediyor';item.progress=completed?100:Math.max(item.progress||0,35);localStorage.setItem('cps-installations',JSON.stringify(installations));render();if(completed){$('#serviceEntryDialog').close();showToast(`${index+1}. Kurulum kaydedildi ve kurulum tamamlandı.`)}else{loadServiceVisit(item,index+1);showToast(`${index+1}. Kurulum kaydedildi. ${index+2}. Kurulum sekmesi açıldı.`)}
});
$('#shipmentForm').addEventListener('submit',event=>{
  if(event.submitter?.value==='cancel')return;
  event.preventDefault();if(currentUser?.role!=='sales'){showToast('Bu işlem için Satış Mühendisi yetkisi gerekir.');return}
  const data=new FormData(event.currentTarget);const partialShipment=data.get('partialShipment')==='on';const shippedProducts=data.getAll('shippedProducts');if(partialShipment&&!shippedProducts.length){showToast('Parçalı sevkiyatta gönderilen en az bir ürün seçilmelidir.');return}
  const item=installations.find(record=>record.id===Number(data.get('installationId')));if(!item)return;item.shipment={productsShipped:data.get('productsShipped')==='on',shipmentDate:data.get('shipmentDate')||null,partialShipment,shippedProducts,demoProductNote:data.get('demoProductNote')||''};
  localStorage.setItem('cps-installations',JSON.stringify(installations));render();$('#shipmentDialog').close();showToast('Sevkiyat bilgileri güncellendi.');
});
$('#orderEditForm').addEventListener('submit',event=>{if(event.submitter?.value==='cancel')return;event.preventDefault();if(currentUser?.role!=='sales'){showToast('Bu işlem için Satış Mühendisi yetkisi gerekir.');return}if(!editOrderProducts.length||editOrderProducts.some(product=>!product.partNo.trim()||!product.description.trim()||!Number(product.qty))){showToast('Her ürün için Part No, Description ve Qty bilgileri zorunludur.');return}const item=installations.find(record=>record.id===Number(new FormData(event.currentTarget).get('installationId')));if(!item)return;item.orderProducts=editOrderProducts.map(product=>({...product}));localStorage.setItem('cps-installations',JSON.stringify(installations));$('#orderEditDialog').close();showToast('Sipariş ürünleri güncellendi.')});

const agenda=[['09:00','Anka Endüstri','1. Kurulum · Gürcan Girgin'],['13:30','Marmara Teknoloji','Ön kontrol · Cihan Eraslan'],['16:00','Eksen Otomasyon','Devam ziyareti · Zemzem Daşdemir']];
$('#agendaList').innerHTML=agenda.map(x=>`<div class="agenda-item"><time>${x[0]}</time><div class="line"></div><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join('');
const alerts=[['Süre aşımı','Eksen Otomasyon planlanan süreyi 4 saat aştı.'],['Eksik ürün','Nova Ambalaj için 2 ürün sevk edilmedi.'],['Geciken rapor','Delta Sistem kurulum raporu bekleniyor.']];
$('#alertsList').innerHTML=alerts.map(x=>`<div class="alert-item"><span class="alert-icon">!</span><div><b>${x[0]}</b><p>${x[1]}</p></div></div>`).join('');

function updateConnection(){const online=navigator.onLine;$('#connectionState').className=`connection ${online?'online':'offline'}`;$('#connectionState span').textContent=online?'Çevrimiçi':'Offline · Sadece görüntüleme';if(!online)showToast('Offline mod: Kayıtlar yalnızca görüntülenebilir.')}
window.addEventListener('online',updateConnection);window.addEventListener('offline',updateConnection);updateConnection();
const savedUser=userDirectory.find(user=>user.username===sessionStorage.getItem('cps-session'));if(savedUser){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');applyUser(savedUser)}
populateUserSelectors();populateInstallationFilters();renderUsers();renderQuickLogins();updateCustomerFields();updateShipmentFields();updateEditShipmentFields();renderOrderProducts();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js');

